#pragma once
//***************************//
//**Chernobyl CRT Simulator**//
//***************************//

#include <iostream>
#include <windows.h>
#include "wavfreq.h"
#include "DockingSubjects.h"


void CRTsim()
{
    system("color 0f");

	gotoxy(0, 0);
	cout << "01:23:07\n" << endl;
	cout << "Turn off Lock Switch" << endl; Beep(mi1, hfpad);
	Sleep(200);
	gotoxy(0, 0);
	cout << "01:23:08";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:09";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:10";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:11" << endl;
	gotoxy(0, 2);
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl; Beep(mi1, hfpad);
	Sleep(200);
	gotoxy(0, 0);
	cout << "01:23:12";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:13";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:14";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:15";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:16";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:17";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:18";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:19";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:20";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:21";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:22";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:23" << endl;
	gotoxy(0, 2);
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl; Beep(mi1, hfpad);
	Sleep(200);
	gotoxy(0, 0);
	cout << "01:23:24";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:25";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:26";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:27";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:28";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:29";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:30";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:31";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:32";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:33";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:34";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:35";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:36";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:37";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:38";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:39";
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:40" << endl;
	gotoxy(0, 2);
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl; Beep(re, oppad);
	gotoxy(0, 2);
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl; //Beep(mi1, oppad);
	Sleep(100);
	gotoxy(0, 2);
	cout << "AR-2 malfunction                       " << endl;
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl; Beep(mi1, oppad);
	gotoxy(0, 2);
	cout << "Relay P1-1332 is connected to the AZ   " << endl; Sleep(100);//Beep(mi1, hxpad);
	cout << "AR-2 malfunction                       " << endl;
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl;
	gotoxy(0, 2);
	cout << "Relay P2-1332 is connected to the AZ   " << endl; Beep(mi1, hfhxpad);
	cout << "Relay P1-1332 is connected to the AZ   " << endl;
	cout << "AR-2 malfunction                       " << endl;
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl;
	gotoxy(0, 2);
	cout << "Relay P2-1332 is in automatic mode     " << endl;
	cout << "Relay P2-1332 is connected to the AZ   " << endl;
	cout << "Relay P1-1332 is connected to the AZ   " << endl;
	cout << "AR-2 malfunction                       " << endl;
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl; //Beep(mi1, hfhxpad);Sleep(40);
	gotoxy(0, 2);
	cout << "Maxium Reactor Function                " << endl; Beep(re, oppad); //hxpad
	cout << "Relay P2-1332 is in automatic mode     " << endl;
	cout << "Relay P2-1332 is connected to the AZ   " << endl;
	cout << "Relay P1-1332 is connected to the AZ   " << endl;
	cout << "AR-2 malfunction                       " << endl;
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl;
	gotoxy(0, 0);
	cout << "01:23:41" << endl;
	gotoxy(0, 2);
	cout << "Turbine generator is not available in the case of pressing AZ-5" << endl;
	cout << "Maxium Reactor Function                " << endl;
	cout << "Relay P2-1332 is in automatic mode     " << endl;
	cout << "Relay P2-1332 is connected to the AZ   " << endl;
	cout << "Relay P1-1332 is connected to the AZ   " << endl;
	cout << "AR-2 malfunction                       " << endl;
	cout << "Poor preparation                       " << endl;
	cout << "AZ-5 SUZ                               " << endl;
	cout << "Reduceing KND1 water injection pressure" << endl;
	cout << "Turn off AR Auto Control Stick" << endl;
	cout << "Turn off Lock Switch" << endl;
	Sleep(800);
	gotoxy(0, 0);
	cout << "01:23:42" << endl;
	Sleep(1000);
	clrscr();
	gotoxy(0, 0);
	cout << "01:23:43\n" << endl;
	cout << "Emergency speed protection activated" << endl; Sleep(40);//Beep(mi1, oppad);
	gotoxy(0, 2);
	cout << "Extreme reactor power" << endl;
	cout << "Emergency speed protection activated" << endl; Sleep(40);//Beep(mi1, oppad);
	gotoxy(0, 2);
	cout << "Emergency power supply turned on 2UZM-4" << endl; Sleep(40);//Beep(mi1, hxpad);
	cout << "Emergency power supply turned on 2UZM-3" << endl;
	cout << "Emergency power supply turned on 2UZM-2" << endl;
	cout << "Emergency power supply turned on 2UZM-1" << endl;
	cout << "Extreme reactor power" << endl;
	cout << "Emergency speed protection activated" << endl;
	gotoxy(0, 2);
	cout << "Emergency power supply turned on 1UZM-4" << endl;
	cout << "Emergency power supply turned on 1UZM-3" << endl;
	cout << "Emergency power supply turned on 1UZM-2" << endl;
	cout << "Emergency power supply turned on 1UZM-1" << endl;
	cout << "Emergency power supply turned on 2UZM-4" << endl;
	cout << "Emergency power supply turned on 2UZM-3" << endl;
	cout << "Emergency power supply turned on 2UZM-2" << endl;
	cout << "Emergency power supply turned on 2UZM-1" << endl;
	cout << "Extreme reactor power" << endl;
	cout << "Emergency speed protection activated" << endl; Beep(mi1, hxpad);
	Sleep(500);
	clrscr();
	gotoxy(0, 0);
	cout << "01:23:44\n" << endl;
	cout << "Failure 2UZM-1" << endl;
	cout << "Failure 2UZM-2" << endl;
	cout << "Failure 2UZM-3" << endl;
	cout << "Failure 2UZM-4" << endl;
	cout << "Failure 1UZM-1" << endl;
	cout << "Failure 1UZM-2" << endl;
	cout << "Failure 1UZM-3" << endl;
	cout << "Failure 1UZM-4" << endl; Beep(re, oppad);
	Sleep(800);
	gotoxy(0, 0);
	cout << "01:23:45\n" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:46\n" << endl;
	Sleep(1000);
	clrscr();
	gotoxy(0, 0);
	cout << "01:23:47\n" << endl;
	cout << "AR-2 damaged" << endl; //Beep(re, oppad);
	gotoxy(0, 2);
	cout << "AR-1 damaged" << endl;
	cout << "AR-2 damaged" << endl; //Beep(re, oppad);
	gotoxy(0, 2);
	cout << "Reactor Core Missing" << endl;
	cout << "AR-1 damaged" << endl;
	cout << "AR-2 damaged" << endl; Beep(re, oppad);
	gotoxy(0, 2);
	cout << "Turbine generators not available" << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Excessive core pressure" << endl;
	cout << "Reactor Core Missing" << endl;
	cout << "AR-1 damaged" << endl;
	cout << "AR-2 damaged" << endl; //Beep(mi1, oppad);
	gotoxy(0, 2);
	cout << "Failure 1UZM-12                 " << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Excessive core pressure" << endl;
	cout << "Reactor Core Missing" << endl;
	cout << "AR-1 damaged" << endl;
	cout << "AR-2 damaged" << endl; Beep(re, oppad);
	Sleep(qtpad);
	gotoxy(0, 0);
	cout << "01:23:48\n" << endl;
	cout << "Autoregulator failure                                          " << endl;
	cout << "Reactor Core Missing                                           " << endl;
	cout << "Turbine generator is not available in the case of pressing AZ-5" << endl;
	cout << "Failure 1UZM-12                 " << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Excessive core pressure" << endl;
	cout << "Reactor Core Missing" << endl;
	cout << "AR-1 damaged" << endl;
	cout << "AR-2 damaged" << endl; Beep(mi1, oppad); //Beep(re, oppad);
	Sleep(oppad);
	gotoxy(0, 0);
	cout << "01:23:49\n" << endl; //Ðè²¹³ä¡£
	cout << "Maxium Reactor Function                                        " << endl;
	cout << "Autoregulator failure                                          " << endl;
	cout << "Reactor Core Missing                                           " << endl;
	cout << "Turbine generator is not available in the case of pressing AZ-5" << endl;
	cout << "Failure 1UZM-12                 " << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Turbine generators not available" << endl;
	cout << "Excessive core pressure" << endl;
	cout << "Reactor Core Missing" << endl;
	cout << "AR-1 damaged" << endl;
	cout << "AR-2 damaged" << endl; Beep(mi1, oppad);
	clrscr();
	cout << "01:23:49\n" << endl;
	cout << "Failure 2UZM-3" << endl;
	cout << "Failure 2UZM-4" << endl;
	cout << "Failure 1UZM-12" << endl;
	cout << "Failure 1UZM-1" << endl;
	cout << "Failure 1UZM-2" << endl;
	cout << "Failure 1UZM-3" << endl;
	cout << "Failure 1UZM-4" << endl; Beep(mi1, oppad);
	cout << "Limited pressure" << endl;
	cout << "Core signal missing" << endl;
	cout << "Sensor cannot get oscillator voltage\nRelay failed" << endl; Beep(re, oppad);
	Sleep(400);
	gotoxy(0, 0);
	cout << "01:23:50" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:51" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:52" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:53" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:54" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:55" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:56" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:57" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:58" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:23:59" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:24:00" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:24:01" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:24:02" << endl;
	Sleep(1000);
	gotoxy(0, 0);
	cout << "01:24:03" << endl;
	Sleep(1000);
	Sleep(2000);
	MessageBox(NULL, "Translation from CSbetaÍæ¼Ò\nSimed by the original video from CSbetaÍæ¼Ò\nMade by Robervert.", "Notice.", MB_OK);

/*

	gotoxy(0, 0);
	cout << "" << endl;
	gotoxy(0, 2);
	cout << "" << endl; Beep(mi1, hxpad);
	//Sleep(1000);
*/
}